version: '3.8'

services:
  neo4j:
    image: neo4j:5
    container_name: neo4j_db
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/password # Default user/password

  insta-graph-app:
    build: .
    container_name: insta_graph_app
    ports:
      - "8080:8080"
    depends_on:
      - neo4j
    environment:
      - SPRING_NEO4J_URI=bolt://neo4j:7687
      - SPRING_NEO4J_AUTHENTICATION_USERNAME=neo4j
      - SPRING_NEO4J_AUTHENTICATION_PASSWORD=password
